<html><body><p>This is the sixth status update about our work on the <a class="reference external" href="https://foss.heptapod.net/pypy/pypy/-/tree/branch/py3k">py3k branch</a>, which we<br>
can work on thanks to all of the people who <a class="reference external" href="http://morepypy.blogspot.com/2012/01/py3k-and-numpy-first-stage-thanks-to.html">donated</a> to the <a class="reference external" href="http://pypy.org/py3donate.html">py3k proposal</a>.</p><p>The coolest news is not about what we did in the past weeks, but what we will<br>
do in the next: I am pleased to announce that <a class="reference external" href="https://twitter.com/pjenvey">Philip Jenvey</a> has been<br>
selected by the PyPy communitiy to be funded for his upcoming work on py3k,<br>
thanks to your generous donations. He will start to work on it shortly, and he<br>
will surely help the branch to make faster progress.  I am also particularly<br>
happy of this because Philip is the first non-core developer who is getting<br>
paid with donations: he demonstrated over the past months to be able to work<br>
effectively on PyPy, and so we were happy to approve his application for the<br>
job.  This means that anyone can potentially be selected in the future, the<br>
only strict requirement is to have a deep interest in working on PyPy and to<br>
prove to be able to do so by contributing to the project.</p><p>Back to the status of the branch. Most of the work since the last status<br>
update has been done in the area of, guess what? Unicode strings. As usual,<br>
this is one of the most important changes between Python 2 and Python 3, so<br>
it's not surprising.  The biggest news is that now PyPy internally supports<br>
unicode identifiers (such as names of variables, functions, attributes, etc.),<br>
whereas earlier it supported only ASCII bytes strings.  The changes is still<br>
barely visible from the outside, because the parser still rejects non-ASCII<br>
identifiers, however you can see it with a bit of creativity:</p><pre class="literal-block">&gt;&gt;&gt;&gt; def foo(x): pass
&gt;&gt;&gt;&gt; foo(**{'àèìòù': 42})
Traceback (most recent call last):
  File "&lt;console&gt;", line 1, in &lt;module&gt;
TypeError: foo() got an unexpected keyword argument 'àèìòù'
</pre><p>Before the latest changes, you used to get question marks instead of the<br>
proper name for the keyword argument.  Although this might seem like a small<br>
detail, it is a big step towards a proper working Python 3 interpreter and it<br>
required a couple of days of headaches.  A spin-off of this work is that now<br>
RPython has better built-in support for unicode (also in the default branch):<br>
for example, it now supports unicode string formatting (using the percent<br>
operator) and the methods <tt class="docutils literal"><span class="pre">.encode/.decode('utf-8')</span></tt>.</p><p>Other than that there is the usual list of smaller issues and bugs that got<br>
fixed, including (but not limited to):</p><blockquote><ul class="simple"><li>teach the compiler when to emit the new opcode <tt class="docutils literal">DELETE_DEREF</tt> (and<br>
implement it!)</li>
<li>detect when we use spaces and TABs inconsistently in the source code, as<br>
CPython does</li>
<li>fix yet another bug related to the new lexically scoped exceptions (this<br>
is the last one, hopefully)</li>
<li>port some of the changes that we did to the standard CPython 2.7 tests to<br>
3.2, to mark those which are implementation details and should not be run on<br>
PyPy</li>
</ul></blockquote><p>Finally, I would like to thank Amaury Forgeot d'Arc and Ariel Ben-Yehuda for<br>
their work on the branch; among other things, Amaury recently worked on<br>
<tt class="docutils literal">cpyext</tt> and on the PyPy <tt class="docutils literal">_cffi_backend</tt>, while Ariel submitted a patch to<br>
implement <a class="reference external" href="http://www.python.org/dev/peps/pep-3138/">PEP 3138</a>.</p></body></html>