<html><body><p>@Maciej:<br><br>PyPy 1.6 worked OK (but it was slower than CPython).<br><br>"we're going to do nothing with that."<br><br>OK<br><br>"Most probably you're using a CPython C extension or some illegal ctypes invocation or older version of jinja that did that or something..."<br><br>I don't think so. GDB says that the EIP register stops at an address which does not seem to belong to the PyPy executable nor to any dynamically loaded library. This leads me to the conclusion that the issue is in the x86 code generated by PyPy.<br><br>"Besides, there is absolutely no point in trying to fix a bug that noone can potentially provide any information for."<br><br>I am not saying you have to fix it. I am just saying that PyPy 1.7 generates code that segfaults.<br><br>Does PyPy employ partial verification when generating x86 code?</p></body></html>